MVCOnlineTicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCOnlineTicariOtomasyon.Models.Sınıflar;
namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.SatisHarekets.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunId.ToString()
                                           }).ToList();
            List<SelectListItem> deger2 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + "" + x.CariSoyad,
                                               Value = x.CariId.ToString()
            
                                           }).ToList();
            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelId.ToString()

                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            
            return View();
        }
        [HttpPost]
        public ActionResult YeniSatis(SatisHareket s)
        {
            s.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SatisHarekets.Add(s);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunId.ToString()
                                           }).ToList();
            List<SelectListItem> deger2 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + "" + x.CariSoyad,
                                               Value = x.CariId.ToString()

                                           }).ToList();
            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelId.ToString()

                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            var deger = c.SatisHarekets.Find(id);
            return View("SatisGetir", deger);
        }
        public ActionResult SatisGuncelle(SatisHareket p)
        {
            var deger = c.SatisHarekets.Find(p.SatisId);
            deger.Cariid = p.Cariid;
            deger.Adet = p.Adet;
            deger.Fiyat = p.Fiyat;
            deger.Personelid = p.Personelid;
            deger.Tarih = p.Tarih;
            deger.ToplamTutar = p.ToplamTutar;
            deger.Urunid = p.Urunid;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisDetay(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.SatisId == id).ToList();
            return View(degerler);
        }
    }
}

MVCOnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using MVCOnlineTicariOtomasyon.Models.Sınıflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<table id="tbl1" class="table table-bordered" style="margin-top:20px">
    <thead>
    <tr>
        <th>ID</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Personel</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Güncelle</th>
        <th>Detaylar</th>

    </tr>
    </thead>
    @foreach (var d in Model)
    {
        <tr>
            <td>@d.SatisId</td>
            <td>@d.Urun.UrunAd</td>
            <td>@d.Carilers.CariAd</td>
            <td>@d.Personel.PersonelAd</td>
            <td>@d.Adet</td>
            <td>@d.Fiyat</td>
            <td>@d.ToplamTutar</td>
            <td>@d.Tarih</td>

            <td><a href="/Satis/SatisGetir/ @d.SatisId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Departman/DepartmanPersonelSatis/@d.Personelid" class="btn btn-default" style="background-color:coral; color:white; ">Detaylar</a></td>

        </tr>
    }
</table>
<a href="/Satis/YeniSatis" class="btn btn-info">Yeni Satış Yap</a>


<link href="~/Content/bootstrap.css" rel="stylesheet" />

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tbl1').dataTable({});
</script>

MVCOnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using MVCOnlineTicariOtomasyon.Models.Sınıflar
@model List<SatisHareket>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Departman Satış Detayı</h2>
<br />
<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.SatisId</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Carilers.CariAd @x.Carilers.CariSoyad</td>
            <th>@x.Personel.PersonelAd  @x.Personel.PersonelSoyad</th>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
        </tr>
    }
</table>
<button class="btn btn-default" style="background-color: dodgerblue">Yazdır</button>

MVCOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Satış İşlemi Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    @Html.HiddenFor(x => x.SatisId)
    @Html.LabelFor(x => x.Urun)
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet)
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.ToplamTutar)
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tarih)
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <button class="btn btn-warning">Güncelle</button>
    <br />
}

MVCOnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.SatisHareket

@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Yeni Ürün Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.Urun)
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.  Personel)
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet)
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tarih)
    @Html.DropDownListFor(x => x.Tarih, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ToplamTutar)
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Satış Yap</button>
    <br />
</form>