MVCOnlineTicariOtomasyon/Models/Sınıflar/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCOnlineTicariOtomasyon.Models.Sınıflar
{
    public class Personel
    {
        [Key]
        public int PersonelId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelAd { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelSoyad { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string PersonelGorsel { get; set; }

        public ICollection<SatisHareket> SatisHarekets { get; set; }
        
        public int Departmanid { get; set; }
        public virtual Departman Departman { get; set; }
    }
}

MVCOnlineTicariOtomasyon/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCOnlineTicariOtomasyon.Models.Sınıflar;

namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Personels.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult PersonelEkle(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.DepartmanId.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }
        [HttpPost]
        public ActionResult PersonelEkle(Personel p)
        {
            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.DepartmanId.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            var prs = c.Personels.Find(id);
            return View("PersonelGetir",prs);
        }
        public ActionResult PersonelGuncelle(Personel p)
        {
            var prsn = c.Personels.Find(p.PersonelId);
            prsn.PersonelAd = p.PersonelAd;
            prsn.PersonelSoyad = p.PersonelSoyad;
            prsn.PersonelGorsel = p.PersonelGorsel;
            prsn.Departmanid = p.Departmanid;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MVCOnlineTicariOtomasyon/Views/Personel/Index.cshtml
@using MVCOnlineTicariOtomasyon.Models.Sınıflar
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Görsel</th>
        <th>Departman</th>
        <th>Güncelle</th>
        <th>Satışlar</th>

    </tr>
    @foreach (var d in Model)
    {
        <tr> 
            <td>@d.PersonelId</td>
            <td>@d.PersonelAd</td>
            <td>@d.PersonelSoyad</td>
            <td>@d.PersonelGorsel</td>
            <td>@d.Departman.DepartmanAd</td>

            <td><a href="/Personel/PersonelGetir/ @d.PersonelId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Departman/DepartmanPersonelSatis/@d.PersonelId" class="btn btn-default" style="background-color:coral; color:white; ">Detaylar</a></td>

        </tr>
    }
</table>
<a href="/Personel/PersonelEkle" class="btn btn-info">Personel Ekle</a>

MVCOnlineTicariOtomasyon/Views/Personel/PersonelEkle.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.Personel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Yeni Personel Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.PersonelAd)
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelSoyad)
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel)
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })
    <br />
   
    @Html.LabelFor(x => x.Departman)
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    @*@Html.TextBoxFor(x => x.Departmanid, new { @class = "form-control" })*@
    
    <button class="btn btn-primary">Kaydet</button>
    <br />
</form>

MVCOnlineTicariOtomasyon/Views/Personel/PersonelGetir.cshtml
@model MVCOnlineTicariOtomasyon.Models.Sınıflar.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Cari Güncelleme Ekranı</h2>
<br />
@using (Html.BeginForm("PersonelGüncelle", "Personel", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.PersonelId)
        @Html.LabelFor(x => x.PersonelAd)
        @Html.LabelFor(x => x.PersonelAd, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PersonelAd, "", new { @style = "color:red" })
        <br />

        @Html.LabelFor(x => x.PersonelSoyad)
        @Html.LabelFor(x => x.PersonelSoyad, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PersonelSoyad, "", new { @style = "color:orange" })
        <br />

        @Html.LabelFor(x => x.PersonelGorsel)
        @Html.LabelFor(x => x.PersonelGorsel, new { @class = "form-control" })
        <br />

        @Html.LabelFor(x => x.Departman)
        @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        <br />
        <button class="btn btn-default" style="background-color:yellowgreen">Güncelle</button>
    </div>

}